# Generated by Django 3.2.7 on 2021-09-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0003_auto_20210930_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='finally_subject',
            field=models.BooleanField(default=False),
        ),
    ]
